env:
   - name: "ENVIRONMENT2"
     value: "Development"
secretEnv:
  - name: SUPERSECRET
    secretKeyRefName: credentials
    secretKeyRefKey: third-password

image:
  registry: docker.io
  repository: emiliork1231/hello-nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
