---
# Source: nginx-hello/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${PROJECT_NAME}
  labels:
    name: ${PROJECT_NAME}
---
# Source: nginx-hello/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  labels:
    name: ${PROJECT_NAME}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ${PROJECT_NAME}
---
# Source: nginx-hello/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    name: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        name: ${PROJECT_NAME}
    spec:
      serviceAccountName: ${PROJECT_NAME}
      securityContext:
        {}
      containers:
        - name: ${PROJECT_NAME}
          securityContext:
            {}
          image: "emiliork1231/hello-nginx"
          imagePullPolicy: IfNotPresent
          env:
            - name: "ENVIRONMENT2"
              value: "Development"
            - name: "SUPERSECRET"
              value: "test"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
---
# Source: nginx-hello/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ${PROJECT_NAME}
  labels:
    name: ${PROJECT_NAME}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['${PROJECT_NAME}:80']
  restartPolicy: Never
