---
# Source: nginx-hello/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  namespace: default
  labels:
    app: ${PROJECT_NAME}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
---
# Source: nginx-hello/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - name: nginx-hello
          image: "emiliork1231/hello-nginx"
          imagePullPolicy: IfNotPresent
          env:
            - name: "ENVIRONMENT2"
              value: "Development"
            - name: "SUPERSECRET"
              value: "test1"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
