apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  replicas: 2
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        image: "emiliork1231/hello-nginx"
        imagePullPolicy: IfNotPresent
        env:
          - name: "ENVIRONMENT2"
            value: "Development"
          - name: "SUPERSECRET"
            value: test1
        ports:
        - containerPort: 80
