---
version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: emiliork1231/hello-nginx
    docker:
      - image: emiliork1231/hello-nginx
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  publish-latest:
    environment:
      IMAGE_NAME: hello-nginx
    docker:
      - image: emiliork1231/hello-nginx:latest
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main
