environments:
  dev:
  stage:

releases:
  - name: nginx-hello
    namespace: {{ .Environment.Name }}
    chart: ./charts/nginx-hello/
    values:
      - ./charts/nginx-hello/values.yaml
      - ./charts/{{ .Environment.Name }}.yaml
      - image:
          tag: {{ requiredEnv "CIRCLE_SHA1" }}      
    secrets:
      - ./charts/nginx-hello/secrets.{{ .Environment.Name }}.yaml
